add extra options to auto_show: Always/Auto/Never
tauri-apps/tauri-plugin-window-state pull request #47
Opened 2022-11-07 20:19 UTC by goenning

Closes #46 

Tested it locally and even if I force visible=false on the .window-state, if I set Show::Always, the app window will become visible when started

2022-11-07 20:23 UTC, FabianLars reviewed
Thank you!

i _think_ we should document the enum variants too (basically the same as on `with_auto_show`), what do you think?

2022-11-07 20:23 UTC, FabianLars commented on src/lib.rs
> +  /// - `Always`: the window will always be shown, regardless of what's the last store state was
```suggestion
  /// - `Always`: the window will always be shown, regardless of what the last store state was
```

2022-11-07 20:27 UTC, goenning commented
> Thank you!
> 
> i _think_ we should document the enum variants too (basically the same as on `with_auto_show`), what do you think?

What if we moved the enum option docs from `with_auto_show` to the enum?

2022-11-07 20:28 UTC, goenning commented
I'm also open to better names: ShowOptions? ShowBehaviour? ShowSettings? just Show?

2022-11-07 20:35 UTC, FabianLars commented
> What if we moved the enum option docs from with_auto_show to the enum?

Would work for me too. Not sure where user's would expect it to be tbh x)

> I'm also open to better names: ShowOptions? ShowBehaviour? ShowSettings? just Show?

idk. `Show` works for me, especially with the variant usage like `Show::Always` it makes sense to me when reading it.

2022-11-07 21:08 UTC, goenning commented
How about now

2022-11-07 21:09 UTC, FabianLars commented
You reintroduced the `what's` typo - other than that i'm quite happy with this version 👍

2022-11-07 21:49 UTC, FabianLars approved these changes

2022-11-07 22:08 UTC, amrbashir requested changes
Thanks, just a few nit-picks

2022-11-07 22:08 UTC, amrbashir commented on src/lib.rs
> +pub enum Show {
```suggestion
pub enum ShowMode {
```

2022-11-07 22:08 UTC, amrbashir commented on src/lib.rs
> +  Auto,
```suggestion
  LastSaved,
```

2022-11-07 22:08 UTC, amrbashir commented on src/lib.rs
> +  fn restore_state(&self, auto_show: Show) -> tauri::Result<()>;
```suggestion
  fn restore_state(&self, show_mode: ShowMode) -> tauri::Result<()>;
```

2022-11-07 22:08 UTC, amrbashir commented on src/lib.rs
> +  auto_show: Show,
```suggestion
  show_mode: Show,
```

2022-11-07 22:08 UTC, amrbashir commented on src/lib.rs
> +  pub fn with_auto_show(mut self, auto_show: Show) -> Self {
```suggestion
  pub fn with_show_mode(mut self, show_mode: ShowMode) -> Self {
```

2022-11-08 05:43 UTC, goenning commented
@amrbashir thanks for the feedback, I've renamed it all 👍

2022-11-08 10:37 UTC, amrbashir approved these changes
Thanks

2022-11-08 10:47 UTC, merged